import { writeFileSync, readdirSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const registryFilePath = path.resolve(__dirname, '../src/lib/Demos/index.js');

const allDemos = readdirSync(
  path.resolve(__dirname, '../src/lib/Demos/')
).filter((file) => file !== 'index.js');

const template = `
  {{name}}: {
    component: () => import('./{{name}}.svelte').then((m) => m.default),
    raw: () => import('./{{name}}.svelte?raw').then((m) => m.default)
  },`;

const fileStart = `// This file is auto-generated by scripts/createDemoRegistry.js
export const registry = {`;
const fileEnd = `\n};\n`;

const registry =
  fileStart +
  allDemos
    .reduce((acc, demo) => {
      return (
        acc +
        template.replace(/{{name}}/g, demo.split('.').slice(0, -1).join('.'))
      );
    }, '')
    .slice(0, -1) +
  fileEnd;

writeFileSync(registryFilePath, registry);

console.log('Demo registry created successfully');
